[workspace]
members = [
    "e1_basic_handler",
    "e2_tls_handler",
    "e3_deffering_commands",
    "e4_followups",
    "e5_manipulating_original_message",
    "e6_components",    
    "e7_embeds",
    "e8_managing_commands",
    "e9_accessing_other_data",
    "e10_modals"
]